# change the port to 8090
server.port=8090

spring.banner.location=classpath:config/banner.txt 

#close the default icon
spring.mvc.favicon.enabled=false 

#there is no need to restart the project
spring.devtools.restart.enabled=false

#open devtools
spring.devtools.livereload.enabled=true

logging.level.com.lx.myself.mapper=debug

#swagger


#druid
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource


#mybatis mapper
mybatis.mapper-locations=classpath:com/lx/myself/mapper/*/*.xml
## MySql auto create table
##create: after system startup,will delete all table,again create table
##none: nothing
##update��system startup will auto decision which table need to created and which fields need to update
mybatis.table.auto=update
##pojo path
mybatis.model.pack=com.lx.myself.pojo
mybatis.database.type=mysql

##mongodb
#spring.data.mongodb.host=127.0.0.1
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=articledb







